### ISSUE TITLE
 Mowzie's Mobs loaded a new chunk$

### ISSUE THREAD

**Issue by RealSenZ0** [BobMowzie/MowziesMobs#123] opened 2019-02-01 03:00 UTC
Mowzie's Mobs loaded a new chunk [-12, -12] in dimension 0 (overworld) while populating chunk [-11, -12], causing cascading worldgen lag.

Times x7

Yup

**Comment by BobMowzie** [comment] 2019-02-01 16:13
Duplicate of #109. Please make sure your issue has not been posted already before creating one next time.

**Closed by BobMowzie** 2019-02-01 16:13 UTC
