### ISSUE TITLE
Unknown Crash - Possibly related to Barakoa Villages

### ISSUE THREAD

**Issue by Sniffity** [BobMowzie/MowziesMobs#357] opened 2021-03-28 07:38 UTC
Unknown crash I experienced after adding Mowzie's Mobs to my server, I believe it is possibly related to Barakoa Villages.

[crash-2021-03-28_03.22.50-server (1).txt](https://github.com/BobMowzie/MowziesMobs/files/6216979/crash-2021-03-28_03.22.50-server.1.txt)

**Comment by BobMowzie** [comment] 2021-03-28 15:52
Duplicate of #326

**Closed by BobMowzie** 2021-03-28 15:52 UTC
