### ISSUE TITLE
Weird crash while trying to fight the Frostmaw with barakoa minions.

### ISSUE THREAD

**Issue by TheMinerBoy** [BobMowzie/MowziesMobs#383] opened 2021-04-01 23:02 UTC
Hi BobMowzie. So I was testing the Frostmaw in a superflat world in Minecraft 1.16.5 using version 1.5.15 when I got this strange crash. I had used the Sol Visage to summon several barakoa to help me.

Crash Logs: [crash-2021-04-01_10.44.32-server.txt](https://github.com/BobMowzie/MowziesMobs/files/6246830/crash-2021-04-01_10.44.32-server.txt)
[crash-2021-04-01_16.19.29-server.txt](https://github.com/BobMowzie/MowziesMobs/files/6246915/crash-2021-04-01_16.19.29-server.txt)
[crash-2021-04-01_16.28.58-server.txt](https://github.com/BobMowzie/MowziesMobs/files/6246916/crash-2021-04-01_16.28.58-server.txt)

Thanks for making an amazing mod!

**Comment by TheMinerBoy** [comment] 2021-04-01 23:32
Okay, so I tried this with only Mowzie's Mobs installed and I still got the crash. It turns out that it only happens when the Frostmaw does its standing slam attack when you have barakoa minions or barakoana minions.

**Comment by TheMinerBoy** [comment] 2021-04-02 00:41
Steps to Reproduce:
- Create a creative mode world
- Summon a Frostmaw
- Find the Sol Visage in the creative inventory and equip it
- Right click while holding another type of mask from this mod
- Go into survival mode
- Let the Frostmaw kill you while the summoned barakoa or barakoana is beside you
- Crash

**Comment by BobMowzie** [comment] 2021-04-02 01:05
Duplicate of #371

**Closed by BobMowzie** 2021-04-02 01:05 UTC

**Comment by BobMowzie** [comment] 2021-04-02 05:23
I think you’ve been commenting on related issues and commits with some further questions, though I can’t see the comments anymore. To clarify, the issue happens when the player dies while Barakoa followers are in combat. The mob being fought is irrelevant. The fix applies to dying to all mobs.
