### ISSUE TITLE
java.lang.NullPointerException: Exception ticking world

### ISSUE THREAD

**Issue by lays24mc** [BobMowzie/MowziesMobs#143] opened 2019-04-03 19:21 UTC
When i used you mod with multimob the game crashed with this crash (see log). 

MowiezMob 1.5.3
MultiMob 1.0.5
Forge 1.12.2 - 2823

Crash report: https://pastebin.com/MjKtbgzX

**Comment by BobMowzie** [comment] 2019-04-03 20:39
Hm, nothing in that log indicates that this crash is caused by Mowzie’s Mobs or Multimob. Are you sure this is either of these mods?

**Comment by lays24mc** [comment] 2019-04-04 07:18
Hi,

this crashlog should be generated. In my server console, I have a conflict with the mob "Nagar" and the mod MultiMob displayed. (sry for my bad english xD)

**Comment by BobMowzie** [comment] 2019-04-04 14:58
This is not a conflict. This is a known bug that has been fixed already. See #130 
The fix will be released in the next version. In the meantime, please turn off the Naga mob.

**Closed by BobMowzie** 2019-04-04 14:58 UTC
