### ISSUE TITLE
Game crashes whenever a Grottol appears

### ISSUE THREAD

**Issue by SubkingExtinct** [BobMowzie/MowziesMobs#367] opened 2021-03-30 01:21 UTC
I have been eagerly waiting to play with this mod for a while now in 1.16, I have been experiencing sudden crashes after exactly 1 or 2 minutes of being in a world, for what i read on the crash report it's apparently because of a grottol spawning, not really sure why it happens whenever i spawn the other creatures nothing happens.

Not to mention i have a datapack that generates the world differently to be exact:
William's Wythers Overhauled Overworld
More Structures Add On For William Wythers Overhauled Overworld
I don't know if these are affecting in any way shape or form, if they are i'd like to know so i can remove them

I will now provide a screenshot of the Mods i've been using along with the mod:
![Captura de pantalla 2021-03-29 193040](https://user-images.githubusercontent.com/73154515/112919993-50979300-90c5-11eb-9038-e5135f6ce3fb.jpg)

And here's the crash log that i got from the crash.
Sorry that the previous picture was on spanish, former Mexican player.
[crash-2021-03-28_18.59.26-server.txt](https://github.com/BobMowzie/MowziesMobs/files/6225505/crash-2021-03-28_18.59.26-server.txt)

**Comment by BobMowzie** [comment] 2021-03-30 01:43
Duplicate of #331

**Closed by BobMowzie** 2021-03-30 01:43 UTC
