### ISSUE TITLE
[crash/compatibility issue] crash when generating Barakoa Village with the  Terraforged world type. 

### ISSUE THREAD

**Issue by Corvus20** [BobMowzie/MowziesMobs#346] opened 2021-03-26 14:01 UTC
Was flying around in creative mode to hunt for bugs in my personal modpack, as well as for bugs in any of the individual mods I had in it. Upon entering a jungle biome, the game crashed. The logs specify some error involving the generation of the Barakoa Village. Have yet to test with this non-terraforged world types, will report back soon.

Crash Log:
[crash-2021-03-26_09.56.52-client.txt](https://github.com/BobMowzie/MowziesMobs/files/6212258/crash-2021-03-26_09.56.52-client.txt)

**Comment by BobMowzie** [comment] 2021-03-26 14:14
Duplicate of #326

**Closed by BobMowzie** 2021-03-26 14:14 UTC
