### ISSUE TITLE
Frostmaw spawning crashing?

### ISSUE THREAD

**Issue by mser7** [BobMowzie/MowziesMobs#45] opened 2018-06-30 02:25 UTC
When I tried to live in a snowy biome, I receive crashes very often, I suspected the issue is related to the Frostmaw, and indeed, after I disable their spawning, the crashes stop completely. Here's one of the client and server crash.

https://pastebin.com/kjLbG0Yw
https://pastebin.com/s3jjYarA

**Comment by BobMowzie** [comment] 2018-06-30 06:57
Duplicate of resolved issue #37. https://github.com/BobMowzie/MowziesMobs/issues/37

**Closed by BobMowzie** 2018-06-30 06:57 UTC
