### ISSUE TITLE
1.16.5 Crash server

### ISSUE THREAD

**Issue by indikogl** [BobMowzie/MowziesMobs#358] opened 2021-03-28 18:27 UTC
Crash in my server

[crash-2021-03-28_09.46.40-server.txt](https://github.com/BobMowzie/MowziesMobs/files/6217837/crash-2021-03-28_09.46.40-server.txt)

**Comment by BobMowzie** [comment] 2021-03-28 18:35
Duplicate of #326

**Closed by BobMowzie** 2021-03-28 18:35 UTC
