### ISSUE TITLE
Wind sound on main menu when both Dungeontweaks and MowziesMobs are installed

### ISSUE THREAD

**Issue by jinkhya** [BobMowzie/MowziesMobs#82] opened 2018-11-03 19:56 UTC
Hello,

I reported an issue between your mod and dungeontweaks, not sure what's causing it.
https://github.com/jredfox/dungeontweeks/issues/16

Thanks in advance !

**Comment by Warrock3280** [comment] 2019-05-08 10:03
Seems like EvilNotchLib or IItemRenderer Reborn causing the issue. Both are required dependencies for DungeonTweaks and SilkSpawners.

**Comment by jredfox** [comment] 2019-05-11 13:37
close this issue as invalid. The issue is caused by EntityIceBall playing a sound inside of the constructor apparently on loop to. I will stop entities from playings sounds before they are added into the world on my side but, this is problematic code and should be really fixed on the mod authors side.

**Comment by BobMowzie** [comment] 2019-05-11 15:01
Thanks. Didn't realize that would cause issues.

**Closed by BobMowzie** 2019-05-11 15:01 UTC
Labels: interaction
