### ISSUE TITLE
modded banner patterns break with Mowzie's installed

### ISSUE THREAD

**Issue by Late-Night** [BobMowzie/MowziesMobs#412] opened 2021-04-18 22:09 UTC

**Comment by wilyank** [comment] 2021-04-19 09:57
Can confirm, banner patterns by Ice and Fire and Alex's Mobs are affected. Additional Banners is not affected.

**Comment by Late-Night** [comment] 2021-04-19 10:04
> 
> 
> Can confirm, banner patterns by Ice and Fire and Alex's Mobs are affected. Additional Banners is not affected.

additional banners broke too for me

**Comment by BobMowzie** [comment] 2021-05-05 06:04
Duplicate of #348

**Closed by BobMowzie** 2021-05-05 06:04 UTC
