### ISSUE TITLE
Frostmaw always spawns twice

### ISSUE THREAD

**Issue by GlowGlew** [BobMowzie/MowziesMobs#497] opened 2021-06-11 02:13 UTC
There are 2 boss bars when you come close to one. Before it wakes up it looks like it is only one, because they spawn in the exact same location. But when it notices you and it stands up it divides in two. This didn't happen once but three times, in the minecraft:snowy_tundra biome. I am playing with the version 1.15.18 of the mod, and have many other mods installed.

**Comment by BobMowzie** [comment] 2021-06-11 04:30
Duplicate of #395
Please remove BGCore until they fix the issue.

**Closed by BobMowzie** 2021-06-11 04:30 UTC
