### ISSUE TITLE
Crash with player spawned Barakoa

### ISSUE THREAD

**Issue by selened** [BobMowzie/MowziesMobs#386] opened 2021-04-04 20:03 UTC
MM version: 1.5.15
Forge version: 36.1.0
Minecraft version: 1.16.5

Problem:
Wearing the Sun Mask and spawning barakoa by right clicking the masks (bliss, fury etc) makes the game crash when you die. Afterwards the save can't be entered again as it crashes again.

How to recreate:
Wear the sun mask and spawn barakoa with their respective masks. Pick a fight with a mob and die to them.

Crash report and forge log after spawning the barakoa:
https://pastebin.com/p4gThKZu (crash report)
https://pastebin.com/RvDsNidn (log)

Crash report and forge log after trying to reenter the world:
https://pastebin.com/P1PpsZrT (crash report)
https://pastebin.com/Rfac8kY9 (log)

**Comment by TheMinerBoy** [comment] 2021-04-05 16:57
This issue will be fixed in the next patch. It is a duplicate of #371.

**Closed** 2021-04-05 18:08 UTC
