### ISSUE TITLE
Compatibility Issue with Biomes O' Plenty Nether

### ISSUE THREAD

**Issue by Reddy64** [BobMowzie/MowziesMobs#352] opened 2021-03-26 17:48 UTC
The mods can run fine together, but world generation is extremely laggy. I've no exact idea why this happens, but it seems also generally, this mod is incompatible with some biome mods like BoP, Outer End. I also notice that the ferrous wroughtnaut spawns in any dimension, which altering the config file does nothing to change.

**Comment by BobMowzie** [comment] 2021-03-30 03:29
Duplicate of #334

**Closed by BobMowzie** 2021-03-30 03:29 UTC
