### ISSUE TITLE
Mob spawning problem and naga spawn egg not working.

### ISSUE THREAD

**Issue by SirAron111** [BobMowzie/MowziesMobs#136] opened 2019-03-22 16:06 UTC
I have 1 Bug and 1 request/problem I want to tell you here if you have the time to look into it.

Here is the Bug  Naga spawn egg doesn’t work on servers I can’t use it on a server but on a single player world it works fine. The other spawn eggs work on server only naga doesn’t.

Second: Mobs don’t spawn in biomes that are similar to their designated biome. For example when using bop you rarely find standard savannas mostly you find things like steppe or outback etc that generate instead of a normal savanna but the barako only spawns in natural savannas this should be made so it also spawns in other biomes that have savanna traits.

The same goes for mobs like the frost maw/the naga/ the jungle plant they just could need some more biome compatibility as well. I even tested it with the spawn chances cranked up to max. meaning I had like 10 barakoas in a savanna and 20 frost maws etc but only in these biomes nagas and plant don’t spawn at all even when setting the spawn chance to 100 (also nagas would do well on mountains or so not only the gravel cliffs you basically never find that biome anyway.)

I tested this biome spawn compat in the standard bop world gen and with the lost cities bop world gen. and some other mods that add biomes. Many modpacks have biome mods making it really hard to even find the mobs from your mod.

**Comment by BobMowzie** [comment] 2019-03-22 16:09
Bug is a duplicate of resolved issue #130. Patch will be released soon.

Feature request is already in the mod. My mob spawns are fully implemented with Forge's Biome Dictionary. Any modded biomes registered with this dictionary will allow my mobs to spawn. If a particular modded biome doesn't work, that mod needs to implement the dictionary or reassign their dictionary tags.

**Closed by BobMowzie** 2019-03-22 16:09 UTC
