### ISSUE TITLE
Barakoana Village Crashes Server whenever any player goes near it

### ISSUE THREAD

**Issue by piecwm** [BobMowzie/MowziesMobs#364] opened 2021-03-29 12:49 UTC
If a player went near the village it would crash the server, if they log in after the crash it would cause another crash.

[crash-2021-03-29_13.05.10-server.txt](https://github.com/BobMowzie/MowziesMobs/files/6221776/crash-2021-03-29_13.05.10-server.txt)
[crash-2021-03-29_00.27.16-server.txt](https://github.com/BobMowzie/MowziesMobs/files/6221777/crash-2021-03-29_00.27.16-server.txt)
[crash-2021-03-29_02.41.15-server.txt](https://github.com/BobMowzie/MowziesMobs/files/6221779/crash-2021-03-29_02.41.15-server.txt)
[crash-2021-03-29_00.16.26-server.txt](https://github.com/BobMowzie/MowziesMobs/files/6221780/crash-2021-03-29_00.16.26-server.txt)

**Comment by piecwm** [comment] 2021-03-29 12:51
I managed to work around the problem by disabling Barakoana through the use of the mowzie's mobs configs and the bad mobs mod.

**Comment by BobMowzie** [comment] 2021-03-29 14:28
Duplicate of #326 
Already fixed for next patch.

**Closed by BobMowzie** 2021-03-29 14:28 UTC
