### ISSUE TITLE
Crash server 1.16

### ISSUE THREAD

**Issue by gm54** [BobMowzie/MowziesMobs#356] opened 2021-03-28 03:35 UTC
when i enter the nether my server crashes

[crash-2021-03-27_22.55.56-server.txt](https://github.com/BobMowzie/MowziesMobs/files/6216816/crash-2021-03-27_22.55.56-server.txt)

**Comment by BobMowzie** [comment] 2021-03-28 15:53
Duplicate of #331

**Closed by BobMowzie** 2021-03-28 15:53 UTC
