### ISSUE TITLE
Crash client when using Undergarden mod [1.16.5]

### ISSUE THREAD

**Issue by IceT2** [BobMowzie/MowziesMobs#362] opened 2021-03-29 01:02 UTC
Running an MC 1.16.5 client with Forge 36.1.2. You can enter the Undergarden dimension without issue if Mowzies is not installed, however, adding Mowzies mobs mod, you are ok in the overworld, but the client crashes the moment you enter the Undergarden dimension.
https://www.curseforge.com/minecraft/mc-mods/the-undergarden

Crash report attached.
[crash-2021-03-29_01.36.40-server.txt](https://github.com/BobMowzie/MowziesMobs/files/6218606/crash-2021-03-29_01.36.40-server.txt)

**Comment by BobMowzie** [comment] 2021-03-29 01:09
Duplicate of #331

**Closed by BobMowzie** 2021-03-29 01:09 UTC
